import Board from '@/components/Board/Board';
import SplashScreen from '@/components/SplashScreen';
import StartGameScreen from '@/components/StartGameScreen';
import Head from 'next/head';
import { useState, useEffect } from 'react';
import { useLanguage } from '@/contexts/LanguageContext';
import { useBackgroundAuth } from '@/hooks/useBackgroundAuth';
import { useUserInfo } from '@/hooks/useUserInfo';

export default function Home() {
  const [showStartScreen, setShowStartScreen] = useState(true);
  const [showSplash, setShowSplash] = useState(false);
  const [showGame, setShowGame] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [fadeOut, setFadeOut] = useState(false);
  const [gameReady, setGameReady] = useState(false);
  const { t } = useLanguage();
  const { isAuthenticated: authAuthenticated, isLoading: authLoading, error: authError } = useBackgroundAuth();
  const { userInfo, isLoading: userInfoLoading, error: userInfoError, isAuthenticated: userInfoAuthenticated } = useUserInfo();

  const handleStartGame = () => {
    setShowStartScreen(false);
    setShowSplash(true);
  };

  const handleSplashComplete = () => {
    setFadeOut(true);
    setTimeout(() => {
      setShowGame(true);
      setTimeout(() => {
        setGameReady(true);
      }, 300);
    }, 800);
  };

  useEffect(() => {
    if (!authLoading && !userInfoLoading) {
      if (authAuthenticated && userInfoAuthenticated) {
        setIsLoading(false);
      } else if (authError || userInfoError) {
        setIsLoading(false);
      } else {
        // Still loading
        setIsLoading(true);
      }
    }
  }, [authAuthenticated, authLoading, authError, userInfoAuthenticated, userInfoLoading, userInfoError]);

  if (isLoading || authLoading || userInfoLoading) {
    return (
      <div style={{
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100vw',
        height: '100vh',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #f5576c 75%, #4facfe 100%)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 9999
      }}>
        <div style={{
          color: 'white',
          fontSize: '1.2rem',
          textAlign: 'center',
          fontFamily: '"TypoGrotek", "Space Grotesk", "Poppins", "Segoe UI", "Roboto", "Helvetica Neue", Arial, sans-serif'
        }}>
          {t('loading')}
        </div>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Bubble Shooter</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div style={{
        position: 'relative',
        width: '100vw',
        height: '100vh',
        overflow: 'hidden'
      }}>
        {/* Start Game Screen */}
        {showStartScreen && (
          <div style={{
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            zIndex: 10000
          }}>
            <StartGameScreen onStart={handleStartGame} />
          </div>
        )}

        {/* Splash Screen */}
        {showSplash && !showGame && (
          <div style={{
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            opacity: fadeOut ? 0 : 1,
            transform: fadeOut ? 'scale(1.1)' : 'scale(1)',
            transition: 'all 0.8s cubic-bezier(0.68, -0.55, 0.265, 1.55)',
            zIndex: 9999,
            pointerEvents: fadeOut ? 'none' : 'auto'
          }}>
            <SplashScreen onComplete={handleSplashComplete} />
          </div>
        )}

        {/* Game with smooth entrance */}
        {showGame && (
          <div style={{
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            opacity: gameReady ? 1 : 0,
            transform: gameReady ? 'translateY(0)' : 'translateY(20px)',
            transition: 'all 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
            zIndex: 1
          }}>
            <Board />
          </div>
        )}
      </div>
    </>
  );
}
