export const GAME_WIDTH: number = 800;
export const GAME_HEIGHT: number = 600;
export const GRID_BORDER_WIDTH: number = GAME_WIDTH - 160;
export const GRID_BORDER_HEIGHT: number = GAME_HEIGHT - 230;
export const GRID_BORDER_START: number = 80;
export const BUBBLE_RADIUS: number = 25;
export const BUBBLE_DIAMETER: number = 50;
export const BUBBLE_SPEED: number = 30;
export const BUBBLE_START_X: number = 400;
export const BUBBLE_START_Y: number = GAME_HEIGHT - BUBBLE_RADIUS;
export const ROW_HEIGHT: number = BUBBLE_DIAMETER * Math.sin(Math.PI / 3);
export const GRID_ROWS: number = 4;
export const GRID_COLUMNS: number = GAME_WIDTH / BUBBLE_DIAMETER - 1; // it must be intergers or u have to manually calculate the number of columns based on the game width and ball diameter.
export const ARROW_LENGTH: number = 150;
export const ARROW_SIZE: number = 30;
export const LIMIT_HEIGHT: number = 9; // for checking game over
export const NUM_NEXT_BUBBLES: number = 2;
export const TIME_COUNT_DOWN: number = 60;
